/**
 * Download Google Fonts as woff2 files for self-hosting.
 * Run once: npx tsx scripts/download-fonts.ts
 */
import fs from 'fs';
import path from 'path';

const FONTS_DIR = path.resolve(process.cwd(), 'public/fonts');

if (!fs.existsSync(FONTS_DIR)) {
    fs.mkdirSync(FONTS_DIR, { recursive: true });
}

// google-webfonts-helper API to get direct woff2 download URLs
const FONTS = [
    {
        id: 'fredoka',
        variants: ['regular'],
        subsets: ['latin'],
        filename: 'fredoka-regular',
    },
    {
        id: 'nunito',
        variants: ['400', '600', '700'],
        subsets: ['latin'],
        filename: 'nunito-v26-latin',
    },
];

async function downloadFont(url: string, dest: string) {
    const resp = await fetch(url);
    if (!resp.ok) throw new Error(`Failed to fetch ${url}: ${resp.status}`);
    const buf = await resp.arrayBuffer();
    fs.writeFileSync(dest, Buffer.from(buf));
    console.log(`  ✅ ${path.basename(dest)}`);
}

async function main() {
    console.log('📥 Downloading fonts from google-webfonts-helper...\n');

    for (const font of FONTS) {
        console.log(`\n🔤 ${font.id}`);
        const apiUrl = `https://gwfh.mranftl.com/api/fonts/${font.id}?subsets=${font.subsets.join(',')}&variants=${font.variants.join(',')}`;
        const resp = await fetch(apiUrl);
        if (!resp.ok) {
            console.error(`  ❌ API error for ${font.id}: ${resp.status}`);
            continue;
        }
        const data: any = await resp.json();

        for (const variant of data.variants || []) {
            if (variant.woff2) {
                const suffix = variant.id === 'regular' ? 'regular' : variant.id;
                const filename = `${font.id}-${suffix}.woff2`;
                const dest = path.join(FONTS_DIR, filename);
                await downloadFont(variant.woff2, dest);
            }
        }
    }

    // Generate the fonts.css file
    const css = generateFontsCss();
    const cssPath = path.resolve(process.cwd(), 'public/fonts/fonts.css');
    fs.writeFileSync(cssPath, css);
    console.log(`\n✅ Written: public/fonts/fonts.css`);
    console.log('\n🎉 Done! Self-hosted fonts ready.');
}

function generateFontsCss(): string {
    return `/* Self-hosted fonts — generated by scripts/download-fonts.ts */

/* Fredoka One — regular 400 */
@font-face {
  font-family: 'Fredoka One';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url('/fonts/fredoka-one-regular.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA,
    U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,
    U+2212, U+2215, U+FEFF, U+FFFD;
}

/* Nunito — 400 */
@font-face {
  font-family: 'Nunito';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url('/fonts/nunito-400.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA,
    U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,
    U+2212, U+2215, U+FEFF, U+FFFD;
}

/* Nunito — 600 */
@font-face {
  font-family: 'Nunito';
  font-style: normal;
  font-weight: 600;
  font-display: swap;
  src: url('/fonts/nunito-600.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA,
    U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,
    U+2212, U+2215, U+FEFF, U+FFFD;
}

/* Nunito — 700 */
@font-face {
  font-family: 'Nunito';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url('/fonts/nunito-700.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA,
    U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,
    U+2212, U+2215, U+FEFF, U+FFFD;
}
`;
}

main().catch(err => {
    console.error(err);
    process.exit(1);
});
